#%RAML 1.0
title: Orders
/order:
  description: "order info"
  get:
    responses:
      200:
        body:
          application/json:
            properties:
              "Id": integer
              "Trackingnumber": integer
  post:
    description: "send order info"
    responses:
      201:
        body:
          application/json:
            properties:
              "orderid": integer
              "orderinfo": string
              "ordertime": time-only
              
                            

              

            

          
